// Code generated by makeservice based on the provided SCDP XML. DO NOT EDIT.

// Package qplay is a generated QPlay package.
package qplay

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:QPlay:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

// State Variables

// Service represents QPlay service.
type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL
	location        *url.URL
	client          *http.Client
}

// NewService creates a new instance of the QPlay service.
// You must provide at least a location URL and an HTTP client using the options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/QPlay/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/QPlay/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

// ControlEndpoint returns the control endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

// EventEndpoint returns the event endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

// Location returns the base URL of the device hosting the service.
func (s *Service) Location() *url.URL {
	return s.location
}

// Client returns the HTTP client used to communicate with the service.
func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName   xml.Name       `xml:"s:Body"`
	QPlayAuth *QPlayAuthArgs `xml:"u:QPlayAuth,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName   xml.Name           `xml:"Body"`
	QPlayAuth *QPlayAuthResponse `xml:"QPlayAuthResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

// QPlayAuth Argument type.
type QPlayAuthArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
	Seed  string `xml:"Seed"`
}

// QPlayAuth Response type.
type QPlayAuthResponse struct {
	Code string `xml:"Code"`
	MID  string `xml:"MID"`
	DID  string `xml:"DID"`
}

// QPlayAuth calls the QPlayAuth action on the service.
func (s *Service) QPlayAuth(args *QPlayAuthArgs) (*QPlayAuthResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("QPlayAuth",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{QPlayAuth: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.QPlayAuth == nil {
		return nil, errors.New("unexpected response from service calling QPlayAuth()")
	}

	return r.Body.QPlayAuth, nil
}

// UpnpEvent represents a UPnP event notification.
type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}

// Property represents a single property in a UPnP event notification.
type Property struct {
	XMLName xml.Name `xml:"property"`
}

// ParseEvent parses a UPnP event notification and updates the service's state variables accordingly.
// It returns a slice of updated state variable values.
func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}

	if err := xml.Unmarshal(body, &evt); err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		}
	}
	return events
}
