// Code generated by makeservice based on the provided SCDP XML. DO NOT EDIT.

// Package virtuallinein is a generated VirtualLineIn package.
package virtuallinein

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:VirtualLineIn:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

// Enumerations

// State Variables
type CurrentTrackMetaData string

// Service represents VirtualLineIn service.
type Service struct {
	controlEndpoint      *url.URL
	eventEndpoint        *url.URL
	CurrentTrackMetaData *CurrentTrackMetaData
	location             *url.URL
	client               *http.Client
}

// NewService creates a new instance of the VirtualLineIn service.
// You must provide at least a location URL and an HTTP client using the options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaRenderer/VirtualLineIn/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaRenderer/VirtualLineIn/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

// ControlEndpoint returns the control endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

// EventEndpoint returns the event endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

// Location returns the base URL of the device hosting the service.
func (s *Service) Location() *url.URL {
	return s.location
}

// Client returns the HTTP client used to communicate with the service.
func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName           xml.Name               `xml:"s:Body"`
	StartTransmission *StartTransmissionArgs `xml:"u:StartTransmission,omitempty"`
	StopTransmission  *StopTransmissionArgs  `xml:"u:StopTransmission,omitempty"`
	Play              *PlayArgs              `xml:"u:Play,omitempty"`
	Pause             *PauseArgs             `xml:"u:Pause,omitempty"`
	Next              *NextArgs              `xml:"u:Next,omitempty"`
	Previous          *PreviousArgs          `xml:"u:Previous,omitempty"`
	Stop              *StopArgs              `xml:"u:Stop,omitempty"`
	SetVolume         *SetVolumeArgs         `xml:"u:SetVolume,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName           xml.Name                   `xml:"Body"`
	StartTransmission *StartTransmissionResponse `xml:"StartTransmissionResponse,omitempty"`
	StopTransmission  *StopTransmissionResponse  `xml:"StopTransmissionResponse,omitempty"`
	Play              *PlayResponse              `xml:"PlayResponse,omitempty"`
	Pause             *PauseResponse             `xml:"PauseResponse,omitempty"`
	Next              *NextResponse              `xml:"NextResponse,omitempty"`
	Previous          *PreviousResponse          `xml:"PreviousResponse,omitempty"`
	Stop              *StopResponse              `xml:"StopResponse,omitempty"`
	SetVolume         *SetVolumeResponse         `xml:"SetVolumeResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

// StartTransmission Argument type.
type StartTransmissionArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	CoordinatorID string `xml:"CoordinatorID"`
}

// StartTransmission Response type.
type StartTransmissionResponse struct {
	CurrentTransportSettings string `xml:"CurrentTransportSettings"`
}

// StartTransmission calls the StartTransmission action on the service.
func (s *Service) StartTransmission(args *StartTransmissionArgs) (*StartTransmissionResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("StartTransmission",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{StartTransmission: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.StartTransmission == nil {
		return nil, errors.New("unexpected response from service calling StartTransmission()")
	}

	return r.Body.StartTransmission, nil
}

// StopTransmission Argument type.
type StopTransmissionArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	CoordinatorID string `xml:"CoordinatorID"`
}

// StopTransmission Response type.
type StopTransmissionResponse struct {
}

// StopTransmission calls the StopTransmission action on the service.
func (s *Service) StopTransmission(args *StopTransmissionArgs) (*StopTransmissionResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("StopTransmission",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{StopTransmission: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.StopTransmission == nil {
		return nil, errors.New("unexpected response from service calling StopTransmission()")
	}

	return r.Body.StopTransmission, nil
}

// Play Argument type.
type PlayArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Speed      string `xml:"Speed"`
}

// Play Response type.
type PlayResponse struct {
}

// Play calls the Play action on the service.
func (s *Service) Play(args *PlayArgs) (*PlayResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Play",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Play: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Play == nil {
		return nil, errors.New("unexpected response from service calling Play()")
	}

	return r.Body.Play, nil
}

// Pause Argument type.
type PauseArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Pause Response type.
type PauseResponse struct {
}

// Pause calls the Pause action on the service.
func (s *Service) Pause(args *PauseArgs) (*PauseResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Pause",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Pause: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Pause == nil {
		return nil, errors.New("unexpected response from service calling Pause()")
	}

	return r.Body.Pause, nil
}

// Next Argument type.
type NextArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Next Response type.
type NextResponse struct {
}

// Next calls the Next action on the service.
func (s *Service) Next(args *NextArgs) (*NextResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Next",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Next: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Next == nil {
		return nil, errors.New("unexpected response from service calling Next()")
	}

	return r.Body.Next, nil
}

// Previous Argument type.
type PreviousArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Previous Response type.
type PreviousResponse struct {
}

// Previous calls the Previous action on the service.
func (s *Service) Previous(args *PreviousArgs) (*PreviousResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Previous",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Previous: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Previous == nil {
		return nil, errors.New("unexpected response from service calling Previous()")
	}

	return r.Body.Previous, nil
}

// Stop Argument type.
type StopArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Stop Response type.
type StopResponse struct {
}

// Stop calls the Stop action on the service.
func (s *Service) Stop(args *StopArgs) (*StopResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Stop",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Stop: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Stop == nil {
		return nil, errors.New("unexpected response from service calling Stop()")
	}

	return r.Body.Stop, nil
}

// SetVolume Argument type.
type SetVolumeArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	DesiredVolume uint16 `xml:"DesiredVolume"`
}

// SetVolume Response type.
type SetVolumeResponse struct {
}

// SetVolume calls the SetVolume action on the service.
func (s *Service) SetVolume(args *SetVolumeArgs) (*SetVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetVolume == nil {
		return nil, errors.New("unexpected response from service calling SetVolume()")
	}

	return r.Body.SetVolume, nil
}

// UpnpEvent represents a UPnP event notification.
type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}

// Property represents a single property in a UPnP event notification.
type Property struct {
	XMLName              xml.Name              `xml:"property"`
	CurrentTrackMetaData *CurrentTrackMetaData `xml:"CurrentTrackMetaData"`
}

// ParseEvent parses a UPnP event notification and updates the service's state variables accordingly.
// It returns a slice of updated state variable values.
func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}

	if err := xml.Unmarshal(body, &evt); err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.CurrentTrackMetaData != nil:
			zp.CurrentTrackMetaData = prop.CurrentTrackMetaData
			events = append(events, *prop.CurrentTrackMetaData)
		}
	}
	return events
}
