// Code generated by makeservice based on the provided SCDP XML. DO NOT EDIT.

// Package avtransport is a generated AVTransport package.
package avtransport

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:AVTransport:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

// State Variables
type LastChange string

// Service represents AVTransport service.
type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL
	LastChange      *LastChange
	location        *url.URL
	client          *http.Client
}

// NewService creates a new instance of the AVTransport service.
// You must provide at least a location URL and an HTTP client using the options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaRenderer/AVTransport/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaRenderer/AVTransport/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

// ControlEndpoint returns the control endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

// EventEndpoint returns the event endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

// Location returns the base URL of the device hosting the service.
func (s *Service) Location() *url.URL {
	return s.location
}

// Client returns the HTTP client used to communicate with the service.
func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                            xml.Name                                `xml:"s:Body"`
	SetAVTransportURI                  *SetAVTransportURIArgs                  `xml:"u:SetAVTransportURI,omitempty"`
	SetNextAVTransportURI              *SetNextAVTransportURIArgs              `xml:"u:SetNextAVTransportURI,omitempty"`
	AddURIToQueue                      *AddURIToQueueArgs                      `xml:"u:AddURIToQueue,omitempty"`
	AddMultipleURIsToQueue             *AddMultipleURIsToQueueArgs             `xml:"u:AddMultipleURIsToQueue,omitempty"`
	ReorderTracksInQueue               *ReorderTracksInQueueArgs               `xml:"u:ReorderTracksInQueue,omitempty"`
	RemoveTrackFromQueue               *RemoveTrackFromQueueArgs               `xml:"u:RemoveTrackFromQueue,omitempty"`
	RemoveTrackRangeFromQueue          *RemoveTrackRangeFromQueueArgs          `xml:"u:RemoveTrackRangeFromQueue,omitempty"`
	RemoveAllTracksFromQueue           *RemoveAllTracksFromQueueArgs           `xml:"u:RemoveAllTracksFromQueue,omitempty"`
	SaveQueue                          *SaveQueueArgs                          `xml:"u:SaveQueue,omitempty"`
	BackupQueue                        *BackupQueueArgs                        `xml:"u:BackupQueue,omitempty"`
	CreateSavedQueue                   *CreateSavedQueueArgs                   `xml:"u:CreateSavedQueue,omitempty"`
	AddURIToSavedQueue                 *AddURIToSavedQueueArgs                 `xml:"u:AddURIToSavedQueue,omitempty"`
	ReorderTracksInSavedQueue          *ReorderTracksInSavedQueueArgs          `xml:"u:ReorderTracksInSavedQueue,omitempty"`
	GetMediaInfo                       *GetMediaInfoArgs                       `xml:"u:GetMediaInfo,omitempty"`
	GetTransportInfo                   *GetTransportInfoArgs                   `xml:"u:GetTransportInfo,omitempty"`
	GetPositionInfo                    *GetPositionInfoArgs                    `xml:"u:GetPositionInfo,omitempty"`
	GetDeviceCapabilities              *GetDeviceCapabilitiesArgs              `xml:"u:GetDeviceCapabilities,omitempty"`
	GetTransportSettings               *GetTransportSettingsArgs               `xml:"u:GetTransportSettings,omitempty"`
	GetCrossfadeMode                   *GetCrossfadeModeArgs                   `xml:"u:GetCrossfadeMode,omitempty"`
	Stop                               *StopArgs                               `xml:"u:Stop,omitempty"`
	Play                               *PlayArgs                               `xml:"u:Play,omitempty"`
	Pause                              *PauseArgs                              `xml:"u:Pause,omitempty"`
	Seek                               *SeekArgs                               `xml:"u:Seek,omitempty"`
	Next                               *NextArgs                               `xml:"u:Next,omitempty"`
	Previous                           *PreviousArgs                           `xml:"u:Previous,omitempty"`
	SetPlayMode                        *SetPlayModeArgs                        `xml:"u:SetPlayMode,omitempty"`
	SetCrossfadeMode                   *SetCrossfadeModeArgs                   `xml:"u:SetCrossfadeMode,omitempty"`
	NotifyDeletedURI                   *NotifyDeletedURIArgs                   `xml:"u:NotifyDeletedURI,omitempty"`
	GetCurrentTransportActions         *GetCurrentTransportActionsArgs         `xml:"u:GetCurrentTransportActions,omitempty"`
	BecomeCoordinatorOfStandaloneGroup *BecomeCoordinatorOfStandaloneGroupArgs `xml:"u:BecomeCoordinatorOfStandaloneGroup,omitempty"`
	DelegateGroupCoordinationTo        *DelegateGroupCoordinationToArgs        `xml:"u:DelegateGroupCoordinationTo,omitempty"`
	BecomeGroupCoordinator             *BecomeGroupCoordinatorArgs             `xml:"u:BecomeGroupCoordinator,omitempty"`
	BecomeGroupCoordinatorAndSource    *BecomeGroupCoordinatorAndSourceArgs    `xml:"u:BecomeGroupCoordinatorAndSource,omitempty"`
	ChangeCoordinator                  *ChangeCoordinatorArgs                  `xml:"u:ChangeCoordinator,omitempty"`
	ChangeTransportSettings            *ChangeTransportSettingsArgs            `xml:"u:ChangeTransportSettings,omitempty"`
	ConfigureSleepTimer                *ConfigureSleepTimerArgs                `xml:"u:ConfigureSleepTimer,omitempty"`
	GetRemainingSleepTimerDuration     *GetRemainingSleepTimerDurationArgs     `xml:"u:GetRemainingSleepTimerDuration,omitempty"`
	RunAlarm                           *RunAlarmArgs                           `xml:"u:RunAlarm,omitempty"`
	StartAutoplay                      *StartAutoplayArgs                      `xml:"u:StartAutoplay,omitempty"`
	GetRunningAlarmProperties          *GetRunningAlarmPropertiesArgs          `xml:"u:GetRunningAlarmProperties,omitempty"`
	SnoozeAlarm                        *SnoozeAlarmArgs                        `xml:"u:SnoozeAlarm,omitempty"`
	EndDirectControlSession            *EndDirectControlSessionArgs            `xml:"u:EndDirectControlSession,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                            xml.Name                                    `xml:"Body"`
	SetAVTransportURI                  *SetAVTransportURIResponse                  `xml:"SetAVTransportURIResponse,omitempty"`
	SetNextAVTransportURI              *SetNextAVTransportURIResponse              `xml:"SetNextAVTransportURIResponse,omitempty"`
	AddURIToQueue                      *AddURIToQueueResponse                      `xml:"AddURIToQueueResponse,omitempty"`
	AddMultipleURIsToQueue             *AddMultipleURIsToQueueResponse             `xml:"AddMultipleURIsToQueueResponse,omitempty"`
	ReorderTracksInQueue               *ReorderTracksInQueueResponse               `xml:"ReorderTracksInQueueResponse,omitempty"`
	RemoveTrackFromQueue               *RemoveTrackFromQueueResponse               `xml:"RemoveTrackFromQueueResponse,omitempty"`
	RemoveTrackRangeFromQueue          *RemoveTrackRangeFromQueueResponse          `xml:"RemoveTrackRangeFromQueueResponse,omitempty"`
	RemoveAllTracksFromQueue           *RemoveAllTracksFromQueueResponse           `xml:"RemoveAllTracksFromQueueResponse,omitempty"`
	SaveQueue                          *SaveQueueResponse                          `xml:"SaveQueueResponse,omitempty"`
	BackupQueue                        *BackupQueueResponse                        `xml:"BackupQueueResponse,omitempty"`
	CreateSavedQueue                   *CreateSavedQueueResponse                   `xml:"CreateSavedQueueResponse,omitempty"`
	AddURIToSavedQueue                 *AddURIToSavedQueueResponse                 `xml:"AddURIToSavedQueueResponse,omitempty"`
	ReorderTracksInSavedQueue          *ReorderTracksInSavedQueueResponse          `xml:"ReorderTracksInSavedQueueResponse,omitempty"`
	GetMediaInfo                       *GetMediaInfoResponse                       `xml:"GetMediaInfoResponse,omitempty"`
	GetTransportInfo                   *GetTransportInfoResponse                   `xml:"GetTransportInfoResponse,omitempty"`
	GetPositionInfo                    *GetPositionInfoResponse                    `xml:"GetPositionInfoResponse,omitempty"`
	GetDeviceCapabilities              *GetDeviceCapabilitiesResponse              `xml:"GetDeviceCapabilitiesResponse,omitempty"`
	GetTransportSettings               *GetTransportSettingsResponse               `xml:"GetTransportSettingsResponse,omitempty"`
	GetCrossfadeMode                   *GetCrossfadeModeResponse                   `xml:"GetCrossfadeModeResponse,omitempty"`
	Stop                               *StopResponse                               `xml:"StopResponse,omitempty"`
	Play                               *PlayResponse                               `xml:"PlayResponse,omitempty"`
	Pause                              *PauseResponse                              `xml:"PauseResponse,omitempty"`
	Seek                               *SeekResponse                               `xml:"SeekResponse,omitempty"`
	Next                               *NextResponse                               `xml:"NextResponse,omitempty"`
	Previous                           *PreviousResponse                           `xml:"PreviousResponse,omitempty"`
	SetPlayMode                        *SetPlayModeResponse                        `xml:"SetPlayModeResponse,omitempty"`
	SetCrossfadeMode                   *SetCrossfadeModeResponse                   `xml:"SetCrossfadeModeResponse,omitempty"`
	NotifyDeletedURI                   *NotifyDeletedURIResponse                   `xml:"NotifyDeletedURIResponse,omitempty"`
	GetCurrentTransportActions         *GetCurrentTransportActionsResponse         `xml:"GetCurrentTransportActionsResponse,omitempty"`
	BecomeCoordinatorOfStandaloneGroup *BecomeCoordinatorOfStandaloneGroupResponse `xml:"BecomeCoordinatorOfStandaloneGroupResponse,omitempty"`
	DelegateGroupCoordinationTo        *DelegateGroupCoordinationToResponse        `xml:"DelegateGroupCoordinationToResponse,omitempty"`
	BecomeGroupCoordinator             *BecomeGroupCoordinatorResponse             `xml:"BecomeGroupCoordinatorResponse,omitempty"`
	BecomeGroupCoordinatorAndSource    *BecomeGroupCoordinatorAndSourceResponse    `xml:"BecomeGroupCoordinatorAndSourceResponse,omitempty"`
	ChangeCoordinator                  *ChangeCoordinatorResponse                  `xml:"ChangeCoordinatorResponse,omitempty"`
	ChangeTransportSettings            *ChangeTransportSettingsResponse            `xml:"ChangeTransportSettingsResponse,omitempty"`
	ConfigureSleepTimer                *ConfigureSleepTimerResponse                `xml:"ConfigureSleepTimerResponse,omitempty"`
	GetRemainingSleepTimerDuration     *GetRemainingSleepTimerDurationResponse     `xml:"GetRemainingSleepTimerDurationResponse,omitempty"`
	RunAlarm                           *RunAlarmResponse                           `xml:"RunAlarmResponse,omitempty"`
	StartAutoplay                      *StartAutoplayResponse                      `xml:"StartAutoplayResponse,omitempty"`
	GetRunningAlarmProperties          *GetRunningAlarmPropertiesResponse          `xml:"GetRunningAlarmPropertiesResponse,omitempty"`
	SnoozeAlarm                        *SnoozeAlarmResponse                        `xml:"SnoozeAlarmResponse,omitempty"`
	EndDirectControlSession            *EndDirectControlSessionResponse            `xml:"EndDirectControlSessionResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

// SetAVTransportURI Argument type.
type SetAVTransportURIArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	InstanceID         uint32 `xml:"InstanceID"`
	CurrentURI         string `xml:"CurrentURI"`
	CurrentURIMetaData string `xml:"CurrentURIMetaData"`
}

// SetAVTransportURI Response type.
type SetAVTransportURIResponse struct {
}

// SetAVTransportURI calls the SetAVTransportURI action on the service.
func (s *Service) SetAVTransportURI(args *SetAVTransportURIArgs) (*SetAVTransportURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetAVTransportURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetAVTransportURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetAVTransportURI == nil {
		return nil, errors.New("unexpected response from service calling SetAVTransportURI()")
	}

	return r.Body.SetAVTransportURI, nil
}

// SetNextAVTransportURI Argument type.
type SetNextAVTransportURIArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	NextURI         string `xml:"NextURI"`
	NextURIMetaData string `xml:"NextURIMetaData"`
}

// SetNextAVTransportURI Response type.
type SetNextAVTransportURIResponse struct {
}

// SetNextAVTransportURI calls the SetNextAVTransportURI action on the service.
func (s *Service) SetNextAVTransportURI(args *SetNextAVTransportURIArgs) (*SetNextAVTransportURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetNextAVTransportURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetNextAVTransportURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetNextAVTransportURI == nil {
		return nil, errors.New("unexpected response from service calling SetNextAVTransportURI()")
	}

	return r.Body.SetNextAVTransportURI, nil
}

// AddURIToQueue Argument type.
type AddURIToQueueArgs struct {
	Xmlns                           string `xml:"xmlns:u,attr"`
	InstanceID                      uint32 `xml:"InstanceID"`
	EnqueuedURI                     string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData             string `xml:"EnqueuedURIMetaData"`
	DesiredFirstTrackNumberEnqueued uint32 `xml:"DesiredFirstTrackNumberEnqueued"`
	EnqueueAsNext                   bool   `xml:"EnqueueAsNext"`
}

// AddURIToQueue Response type.
type AddURIToQueueResponse struct {
	FirstTrackNumberEnqueued uint32 `xml:"FirstTrackNumberEnqueued"`
	NumTracksAdded           uint32 `xml:"NumTracksAdded"`
	NewQueueLength           uint32 `xml:"NewQueueLength"`
}

// AddURIToQueue calls the AddURIToQueue action on the service.
func (s *Service) AddURIToQueue(args *AddURIToQueueArgs) (*AddURIToQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddURIToQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddURIToQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddURIToQueue == nil {
		return nil, errors.New("unexpected response from service calling AddURIToQueue()")
	}

	return r.Body.AddURIToQueue, nil
}

// AddMultipleURIsToQueue Argument type.
type AddMultipleURIsToQueueArgs struct {
	Xmlns                           string `xml:"xmlns:u,attr"`
	InstanceID                      uint32 `xml:"InstanceID"`
	UpdateID                        uint32 `xml:"UpdateID"`
	NumberOfURIs                    uint32 `xml:"NumberOfURIs"`
	EnqueuedURIs                    string `xml:"EnqueuedURIs"`
	EnqueuedURIsMetaData            string `xml:"EnqueuedURIsMetaData"`
	ContainerURI                    string `xml:"ContainerURI"`
	ContainerMetaData               string `xml:"ContainerMetaData"`
	DesiredFirstTrackNumberEnqueued uint32 `xml:"DesiredFirstTrackNumberEnqueued"`
	EnqueueAsNext                   bool   `xml:"EnqueueAsNext"`
}

// AddMultipleURIsToQueue Response type.
type AddMultipleURIsToQueueResponse struct {
	FirstTrackNumberEnqueued uint32 `xml:"FirstTrackNumberEnqueued"`
	NumTracksAdded           uint32 `xml:"NumTracksAdded"`
	NewQueueLength           uint32 `xml:"NewQueueLength"`
	NewUpdateID              uint32 `xml:"NewUpdateID"`
}

// AddMultipleURIsToQueue calls the AddMultipleURIsToQueue action on the service.
func (s *Service) AddMultipleURIsToQueue(args *AddMultipleURIsToQueueArgs) (*AddMultipleURIsToQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddMultipleURIsToQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddMultipleURIsToQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddMultipleURIsToQueue == nil {
		return nil, errors.New("unexpected response from service calling AddMultipleURIsToQueue()")
	}

	return r.Body.AddMultipleURIsToQueue, nil
}

// ReorderTracksInQueue Argument type.
type ReorderTracksInQueueArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	StartingIndex  uint32 `xml:"StartingIndex"`
	NumberOfTracks uint32 `xml:"NumberOfTracks"`
	InsertBefore   uint32 `xml:"InsertBefore"`
	UpdateID       uint32 `xml:"UpdateID"`
}

// ReorderTracksInQueue Response type.
type ReorderTracksInQueueResponse struct {
}

// ReorderTracksInQueue calls the ReorderTracksInQueue action on the service.
func (s *Service) ReorderTracksInQueue(args *ReorderTracksInQueueArgs) (*ReorderTracksInQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ReorderTracksInQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ReorderTracksInQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ReorderTracksInQueue == nil {
		return nil, errors.New("unexpected response from service calling ReorderTracksInQueue()")
	}

	return r.Body.ReorderTracksInQueue, nil
}

// RemoveTrackFromQueue Argument type.
type RemoveTrackFromQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	ObjectID   string `xml:"ObjectID"`
	UpdateID   uint32 `xml:"UpdateID"`
}

// RemoveTrackFromQueue Response type.
type RemoveTrackFromQueueResponse struct {
}

// RemoveTrackFromQueue calls the RemoveTrackFromQueue action on the service.
func (s *Service) RemoveTrackFromQueue(args *RemoveTrackFromQueueArgs) (*RemoveTrackFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveTrackFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveTrackFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveTrackFromQueue == nil {
		return nil, errors.New("unexpected response from service calling RemoveTrackFromQueue()")
	}

	return r.Body.RemoveTrackFromQueue, nil
}

// RemoveTrackRangeFromQueue Argument type.
type RemoveTrackRangeFromQueueArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	UpdateID       uint32 `xml:"UpdateID"`
	StartingIndex  uint32 `xml:"StartingIndex"`
	NumberOfTracks uint32 `xml:"NumberOfTracks"`
}

// RemoveTrackRangeFromQueue Response type.
type RemoveTrackRangeFromQueueResponse struct {
	NewUpdateID uint32 `xml:"NewUpdateID"`
}

// RemoveTrackRangeFromQueue calls the RemoveTrackRangeFromQueue action on the service.
func (s *Service) RemoveTrackRangeFromQueue(args *RemoveTrackRangeFromQueueArgs) (*RemoveTrackRangeFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveTrackRangeFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveTrackRangeFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveTrackRangeFromQueue == nil {
		return nil, errors.New("unexpected response from service calling RemoveTrackRangeFromQueue()")
	}

	return r.Body.RemoveTrackRangeFromQueue, nil
}

// RemoveAllTracksFromQueue Argument type.
type RemoveAllTracksFromQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// RemoveAllTracksFromQueue Response type.
type RemoveAllTracksFromQueueResponse struct {
}

// RemoveAllTracksFromQueue calls the RemoveAllTracksFromQueue action on the service.
func (s *Service) RemoveAllTracksFromQueue(args *RemoveAllTracksFromQueueArgs) (*RemoveAllTracksFromQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RemoveAllTracksFromQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RemoveAllTracksFromQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RemoveAllTracksFromQueue == nil {
		return nil, errors.New("unexpected response from service calling RemoveAllTracksFromQueue()")
	}

	return r.Body.RemoveAllTracksFromQueue, nil
}

// SaveQueue Argument type.
type SaveQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Title      string `xml:"Title"`
	ObjectID   string `xml:"ObjectID"`
}

// SaveQueue Response type.
type SaveQueueResponse struct {
	AssignedObjectID string `xml:"AssignedObjectID"`
}

// SaveQueue calls the SaveQueue action on the service.
func (s *Service) SaveQueue(args *SaveQueueArgs) (*SaveQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SaveQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SaveQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SaveQueue == nil {
		return nil, errors.New("unexpected response from service calling SaveQueue()")
	}

	return r.Body.SaveQueue, nil
}

// BackupQueue Argument type.
type BackupQueueArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// BackupQueue Response type.
type BackupQueueResponse struct {
}

// BackupQueue calls the BackupQueue action on the service.
func (s *Service) BackupQueue(args *BackupQueueArgs) (*BackupQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BackupQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BackupQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BackupQueue == nil {
		return nil, errors.New("unexpected response from service calling BackupQueue()")
	}

	return r.Body.BackupQueue, nil
}

// CreateSavedQueue Argument type.
type CreateSavedQueueArgs struct {
	Xmlns               string `xml:"xmlns:u,attr"`
	InstanceID          uint32 `xml:"InstanceID"`
	Title               string `xml:"Title"`
	EnqueuedURI         string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData string `xml:"EnqueuedURIMetaData"`
}

// CreateSavedQueue Response type.
type CreateSavedQueueResponse struct {
	NumTracksAdded   uint32 `xml:"NumTracksAdded"`
	NewQueueLength   uint32 `xml:"NewQueueLength"`
	AssignedObjectID string `xml:"AssignedObjectID"`
	NewUpdateID      uint32 `xml:"NewUpdateID"`
}

// CreateSavedQueue calls the CreateSavedQueue action on the service.
func (s *Service) CreateSavedQueue(args *CreateSavedQueueArgs) (*CreateSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("CreateSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{CreateSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.CreateSavedQueue == nil {
		return nil, errors.New("unexpected response from service calling CreateSavedQueue()")
	}

	return r.Body.CreateSavedQueue, nil
}

// AddURIToSavedQueue Argument type.
type AddURIToSavedQueueArgs struct {
	Xmlns               string `xml:"xmlns:u,attr"`
	InstanceID          uint32 `xml:"InstanceID"`
	ObjectID            string `xml:"ObjectID"`
	UpdateID            uint32 `xml:"UpdateID"`
	EnqueuedURI         string `xml:"EnqueuedURI"`
	EnqueuedURIMetaData string `xml:"EnqueuedURIMetaData"`
	AddAtIndex          uint32 `xml:"AddAtIndex"`
}

// AddURIToSavedQueue Response type.
type AddURIToSavedQueueResponse struct {
	NumTracksAdded uint32 `xml:"NumTracksAdded"`
	NewQueueLength uint32 `xml:"NewQueueLength"`
	NewUpdateID    uint32 `xml:"NewUpdateID"`
}

// AddURIToSavedQueue calls the AddURIToSavedQueue action on the service.
func (s *Service) AddURIToSavedQueue(args *AddURIToSavedQueueArgs) (*AddURIToSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("AddURIToSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{AddURIToSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.AddURIToSavedQueue == nil {
		return nil, errors.New("unexpected response from service calling AddURIToSavedQueue()")
	}

	return r.Body.AddURIToSavedQueue, nil
}

// ReorderTracksInSavedQueue Argument type.
type ReorderTracksInSavedQueueArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	ObjectID        string `xml:"ObjectID"`
	UpdateID        uint32 `xml:"UpdateID"`
	TrackList       string `xml:"TrackList"`
	NewPositionList string `xml:"NewPositionList"`
}

// ReorderTracksInSavedQueue Response type.
type ReorderTracksInSavedQueueResponse struct {
	QueueLengthChange int32  `xml:"QueueLengthChange"`
	NewQueueLength    uint32 `xml:"NewQueueLength"`
	NewUpdateID       uint32 `xml:"NewUpdateID"`
}

// ReorderTracksInSavedQueue calls the ReorderTracksInSavedQueue action on the service.
func (s *Service) ReorderTracksInSavedQueue(args *ReorderTracksInSavedQueueArgs) (*ReorderTracksInSavedQueueResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ReorderTracksInSavedQueue",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ReorderTracksInSavedQueue: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ReorderTracksInSavedQueue == nil {
		return nil, errors.New("unexpected response from service calling ReorderTracksInSavedQueue()")
	}

	return r.Body.ReorderTracksInSavedQueue, nil
}

// GetMediaInfo Argument type.
type GetMediaInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetMediaInfo Response type.
type GetMediaInfoResponse struct {
	NrTracks           uint32 `xml:"NrTracks"`
	MediaDuration      string `xml:"MediaDuration"`
	CurrentURI         string `xml:"CurrentURI"`
	CurrentURIMetaData string `xml:"CurrentURIMetaData"`
	NextURI            string `xml:"NextURI"`
	NextURIMetaData    string `xml:"NextURIMetaData"`
	PlayMedium         string `xml:"PlayMedium"`
	RecordMedium       string `xml:"RecordMedium"`
	WriteStatus        string `xml:"WriteStatus"`
}

// GetMediaInfo calls the GetMediaInfo action on the service.
func (s *Service) GetMediaInfo(args *GetMediaInfoArgs) (*GetMediaInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetMediaInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetMediaInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetMediaInfo == nil {
		return nil, errors.New("unexpected response from service calling GetMediaInfo()")
	}

	return r.Body.GetMediaInfo, nil
}

// GetTransportInfo Argument type.
type GetTransportInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetTransportInfo Response type.
type GetTransportInfoResponse struct {
	CurrentTransportState  string `xml:"CurrentTransportState"`
	CurrentTransportStatus string `xml:"CurrentTransportStatus"`
	CurrentSpeed           string `xml:"CurrentSpeed"`
}

// GetTransportInfo calls the GetTransportInfo action on the service.
func (s *Service) GetTransportInfo(args *GetTransportInfoArgs) (*GetTransportInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTransportInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTransportInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTransportInfo == nil {
		return nil, errors.New("unexpected response from service calling GetTransportInfo()")
	}

	return r.Body.GetTransportInfo, nil
}

// GetPositionInfo Argument type.
type GetPositionInfoArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetPositionInfo Response type.
type GetPositionInfoResponse struct {
	Track         uint32 `xml:"Track"`
	TrackDuration string `xml:"TrackDuration"`
	TrackMetaData string `xml:"TrackMetaData"`
	TrackURI      string `xml:"TrackURI"`
	RelTime       string `xml:"RelTime"`
	AbsTime       string `xml:"AbsTime"`
	RelCount      int32  `xml:"RelCount"`
	AbsCount      int32  `xml:"AbsCount"`
}

// GetPositionInfo calls the GetPositionInfo action on the service.
func (s *Service) GetPositionInfo(args *GetPositionInfoArgs) (*GetPositionInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetPositionInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetPositionInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetPositionInfo == nil {
		return nil, errors.New("unexpected response from service calling GetPositionInfo()")
	}

	return r.Body.GetPositionInfo, nil
}

// GetDeviceCapabilities Argument type.
type GetDeviceCapabilitiesArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetDeviceCapabilities Response type.
type GetDeviceCapabilitiesResponse struct {
	PlayMedia       string `xml:"PlayMedia"`
	RecMedia        string `xml:"RecMedia"`
	RecQualityModes string `xml:"RecQualityModes"`
}

// GetDeviceCapabilities calls the GetDeviceCapabilities action on the service.
func (s *Service) GetDeviceCapabilities(args *GetDeviceCapabilitiesArgs) (*GetDeviceCapabilitiesResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetDeviceCapabilities",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetDeviceCapabilities: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetDeviceCapabilities == nil {
		return nil, errors.New("unexpected response from service calling GetDeviceCapabilities()")
	}

	return r.Body.GetDeviceCapabilities, nil
}

// GetTransportSettings Argument type.
type GetTransportSettingsArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetTransportSettings Response type.
type GetTransportSettingsResponse struct {
	PlayMode       string `xml:"PlayMode"`
	RecQualityMode string `xml:"RecQualityMode"`
}

// GetTransportSettings calls the GetTransportSettings action on the service.
func (s *Service) GetTransportSettings(args *GetTransportSettingsArgs) (*GetTransportSettingsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTransportSettings",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTransportSettings: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTransportSettings == nil {
		return nil, errors.New("unexpected response from service calling GetTransportSettings()")
	}

	return r.Body.GetTransportSettings, nil
}

// GetCrossfadeMode Argument type.
type GetCrossfadeModeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetCrossfadeMode Response type.
type GetCrossfadeModeResponse struct {
	CrossfadeMode bool `xml:"CrossfadeMode"`
}

// GetCrossfadeMode calls the GetCrossfadeMode action on the service.
func (s *Service) GetCrossfadeMode(args *GetCrossfadeModeArgs) (*GetCrossfadeModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCrossfadeMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCrossfadeMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCrossfadeMode == nil {
		return nil, errors.New("unexpected response from service calling GetCrossfadeMode()")
	}

	return r.Body.GetCrossfadeMode, nil
}

// Stop Argument type.
type StopArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Stop Response type.
type StopResponse struct {
}

// Stop calls the Stop action on the service.
func (s *Service) Stop(args *StopArgs) (*StopResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Stop",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Stop: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Stop == nil {
		return nil, errors.New("unexpected response from service calling Stop()")
	}

	return r.Body.Stop, nil
}

// Play Argument type.
type PlayArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Speed      string `xml:"Speed"`
}

// Play Response type.
type PlayResponse struct {
}

// Play calls the Play action on the service.
func (s *Service) Play(args *PlayArgs) (*PlayResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Play",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Play: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Play == nil {
		return nil, errors.New("unexpected response from service calling Play()")
	}

	return r.Body.Play, nil
}

// Pause Argument type.
type PauseArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Pause Response type.
type PauseResponse struct {
}

// Pause calls the Pause action on the service.
func (s *Service) Pause(args *PauseArgs) (*PauseResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Pause",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Pause: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Pause == nil {
		return nil, errors.New("unexpected response from service calling Pause()")
	}

	return r.Body.Pause, nil
}

// Seek Argument type.
type SeekArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Unit       string `xml:"Unit"`
	Target     string `xml:"Target"`
}

// Seek Response type.
type SeekResponse struct {
}

// Seek calls the Seek action on the service.
func (s *Service) Seek(args *SeekArgs) (*SeekResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Seek",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Seek: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Seek == nil {
		return nil, errors.New("unexpected response from service calling Seek()")
	}

	return r.Body.Seek, nil
}

// Next Argument type.
type NextArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Next Response type.
type NextResponse struct {
}

// Next calls the Next action on the service.
func (s *Service) Next(args *NextArgs) (*NextResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Next",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Next: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Next == nil {
		return nil, errors.New("unexpected response from service calling Next()")
	}

	return r.Body.Next, nil
}

// Previous Argument type.
type PreviousArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// Previous Response type.
type PreviousResponse struct {
}

// Previous calls the Previous action on the service.
func (s *Service) Previous(args *PreviousArgs) (*PreviousResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("Previous",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{Previous: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.Previous == nil {
		return nil, errors.New("unexpected response from service calling Previous()")
	}

	return r.Body.Previous, nil
}

// SetPlayMode Argument type.
type SetPlayModeArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	InstanceID  uint32 `xml:"InstanceID"`
	NewPlayMode string `xml:"NewPlayMode"`
}

// SetPlayMode Response type.
type SetPlayModeResponse struct {
}

// SetPlayMode calls the SetPlayMode action on the service.
func (s *Service) SetPlayMode(args *SetPlayModeArgs) (*SetPlayModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetPlayMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetPlayMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetPlayMode == nil {
		return nil, errors.New("unexpected response from service calling SetPlayMode()")
	}

	return r.Body.SetPlayMode, nil
}

// SetCrossfadeMode Argument type.
type SetCrossfadeModeArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	CrossfadeMode bool   `xml:"CrossfadeMode"`
}

// SetCrossfadeMode Response type.
type SetCrossfadeModeResponse struct {
}

// SetCrossfadeMode calls the SetCrossfadeMode action on the service.
func (s *Service) SetCrossfadeMode(args *SetCrossfadeModeArgs) (*SetCrossfadeModeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetCrossfadeMode",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetCrossfadeMode: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetCrossfadeMode == nil {
		return nil, errors.New("unexpected response from service calling SetCrossfadeMode()")
	}

	return r.Body.SetCrossfadeMode, nil
}

// NotifyDeletedURI Argument type.
type NotifyDeletedURIArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	DeletedURI string `xml:"DeletedURI"`
}

// NotifyDeletedURI Response type.
type NotifyDeletedURIResponse struct {
}

// NotifyDeletedURI calls the NotifyDeletedURI action on the service.
func (s *Service) NotifyDeletedURI(args *NotifyDeletedURIArgs) (*NotifyDeletedURIResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("NotifyDeletedURI",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{NotifyDeletedURI: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.NotifyDeletedURI == nil {
		return nil, errors.New("unexpected response from service calling NotifyDeletedURI()")
	}

	return r.Body.NotifyDeletedURI, nil
}

// GetCurrentTransportActions Argument type.
type GetCurrentTransportActionsArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetCurrentTransportActions Response type.
type GetCurrentTransportActionsResponse struct {
	Actions string `xml:"Actions"`
}

// GetCurrentTransportActions calls the GetCurrentTransportActions action on the service.
func (s *Service) GetCurrentTransportActions(args *GetCurrentTransportActionsArgs) (*GetCurrentTransportActionsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCurrentTransportActions",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCurrentTransportActions: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCurrentTransportActions == nil {
		return nil, errors.New("unexpected response from service calling GetCurrentTransportActions()")
	}

	return r.Body.GetCurrentTransportActions, nil
}

// BecomeCoordinatorOfStandaloneGroup Argument type.
type BecomeCoordinatorOfStandaloneGroupArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// BecomeCoordinatorOfStandaloneGroup Response type.
type BecomeCoordinatorOfStandaloneGroupResponse struct {
	DelegatedGroupCoordinatorID string `xml:"DelegatedGroupCoordinatorID"`
	NewGroupID                  string `xml:"NewGroupID"`
}

// BecomeCoordinatorOfStandaloneGroup calls the BecomeCoordinatorOfStandaloneGroup action on the service.
func (s *Service) BecomeCoordinatorOfStandaloneGroup(args *BecomeCoordinatorOfStandaloneGroupArgs) (*BecomeCoordinatorOfStandaloneGroupResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeCoordinatorOfStandaloneGroup",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeCoordinatorOfStandaloneGroup: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeCoordinatorOfStandaloneGroup == nil {
		return nil, errors.New("unexpected response from service calling BecomeCoordinatorOfStandaloneGroup()")
	}

	return r.Body.BecomeCoordinatorOfStandaloneGroup, nil
}

// DelegateGroupCoordinationTo Argument type.
type DelegateGroupCoordinationToArgs struct {
	Xmlns          string `xml:"xmlns:u,attr"`
	InstanceID     uint32 `xml:"InstanceID"`
	NewCoordinator string `xml:"NewCoordinator"`
	RejoinGroup    bool   `xml:"RejoinGroup"`
}

// DelegateGroupCoordinationTo Response type.
type DelegateGroupCoordinationToResponse struct {
}

// DelegateGroupCoordinationTo calls the DelegateGroupCoordinationTo action on the service.
func (s *Service) DelegateGroupCoordinationTo(args *DelegateGroupCoordinationToArgs) (*DelegateGroupCoordinationToResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("DelegateGroupCoordinationTo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{DelegateGroupCoordinationTo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.DelegateGroupCoordinationTo == nil {
		return nil, errors.New("unexpected response from service calling DelegateGroupCoordinationTo()")
	}

	return r.Body.DelegateGroupCoordinationTo, nil
}

// BecomeGroupCoordinator Argument type.
type BecomeGroupCoordinatorArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	CurrentGroupID        string `xml:"CurrentGroupID"`
	OtherMembers          string `xml:"OtherMembers"`
	TransportSettings     string `xml:"TransportSettings"`
	CurrentURI            string `xml:"CurrentURI"`
	CurrentURIMetaData    string `xml:"CurrentURIMetaData"`
	SleepTimerState       string `xml:"SleepTimerState"`
	AlarmState            string `xml:"AlarmState"`
	StreamRestartState    string `xml:"StreamRestartState"`
	CurrentQueueTrackList string `xml:"CurrentQueueTrackList"`
	CurrentVLIState       string `xml:"CurrentVLIState"`
}

// BecomeGroupCoordinator Response type.
type BecomeGroupCoordinatorResponse struct {
}

// BecomeGroupCoordinator calls the BecomeGroupCoordinator action on the service.
func (s *Service) BecomeGroupCoordinator(args *BecomeGroupCoordinatorArgs) (*BecomeGroupCoordinatorResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeGroupCoordinator",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeGroupCoordinator: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeGroupCoordinator == nil {
		return nil, errors.New("unexpected response from service calling BecomeGroupCoordinator()")
	}

	return r.Body.BecomeGroupCoordinator, nil
}

// BecomeGroupCoordinatorAndSource Argument type.
type BecomeGroupCoordinatorAndSourceArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	CurrentGroupID        string `xml:"CurrentGroupID"`
	OtherMembers          string `xml:"OtherMembers"`
	CurrentURI            string `xml:"CurrentURI"`
	CurrentURIMetaData    string `xml:"CurrentURIMetaData"`
	SleepTimerState       string `xml:"SleepTimerState"`
	AlarmState            string `xml:"AlarmState"`
	StreamRestartState    string `xml:"StreamRestartState"`
	CurrentAVTTrackList   string `xml:"CurrentAVTTrackList"`
	CurrentQueueTrackList string `xml:"CurrentQueueTrackList"`
	CurrentSourceState    string `xml:"CurrentSourceState"`
	ResumePlayback        bool   `xml:"ResumePlayback"`
}

// BecomeGroupCoordinatorAndSource Response type.
type BecomeGroupCoordinatorAndSourceResponse struct {
}

// BecomeGroupCoordinatorAndSource calls the BecomeGroupCoordinatorAndSource action on the service.
func (s *Service) BecomeGroupCoordinatorAndSource(args *BecomeGroupCoordinatorAndSourceArgs) (*BecomeGroupCoordinatorAndSourceResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("BecomeGroupCoordinatorAndSource",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{BecomeGroupCoordinatorAndSource: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.BecomeGroupCoordinatorAndSource == nil {
		return nil, errors.New("unexpected response from service calling BecomeGroupCoordinatorAndSource()")
	}

	return r.Body.BecomeGroupCoordinatorAndSource, nil
}

// ChangeCoordinator Argument type.
type ChangeCoordinatorArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	CurrentCoordinator    string `xml:"CurrentCoordinator"`
	NewCoordinator        string `xml:"NewCoordinator"`
	NewTransportSettings  string `xml:"NewTransportSettings"`
	CurrentAVTransportURI string `xml:"CurrentAVTransportURI"`
}

// ChangeCoordinator Response type.
type ChangeCoordinatorResponse struct {
}

// ChangeCoordinator calls the ChangeCoordinator action on the service.
func (s *Service) ChangeCoordinator(args *ChangeCoordinatorArgs) (*ChangeCoordinatorResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ChangeCoordinator",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ChangeCoordinator: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ChangeCoordinator == nil {
		return nil, errors.New("unexpected response from service calling ChangeCoordinator()")
	}

	return r.Body.ChangeCoordinator, nil
}

// ChangeTransportSettings Argument type.
type ChangeTransportSettingsArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	NewTransportSettings  string `xml:"NewTransportSettings"`
	CurrentAVTransportURI string `xml:"CurrentAVTransportURI"`
}

// ChangeTransportSettings Response type.
type ChangeTransportSettingsResponse struct {
}

// ChangeTransportSettings calls the ChangeTransportSettings action on the service.
func (s *Service) ChangeTransportSettings(args *ChangeTransportSettingsArgs) (*ChangeTransportSettingsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ChangeTransportSettings",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ChangeTransportSettings: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ChangeTransportSettings == nil {
		return nil, errors.New("unexpected response from service calling ChangeTransportSettings()")
	}

	return r.Body.ChangeTransportSettings, nil
}

// ConfigureSleepTimer Argument type.
type ConfigureSleepTimerArgs struct {
	Xmlns                 string `xml:"xmlns:u,attr"`
	InstanceID            uint32 `xml:"InstanceID"`
	NewSleepTimerDuration string `xml:"NewSleepTimerDuration"`
}

// ConfigureSleepTimer Response type.
type ConfigureSleepTimerResponse struct {
}

// ConfigureSleepTimer calls the ConfigureSleepTimer action on the service.
func (s *Service) ConfigureSleepTimer(args *ConfigureSleepTimerArgs) (*ConfigureSleepTimerResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ConfigureSleepTimer",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ConfigureSleepTimer: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ConfigureSleepTimer == nil {
		return nil, errors.New("unexpected response from service calling ConfigureSleepTimer()")
	}

	return r.Body.ConfigureSleepTimer, nil
}

// GetRemainingSleepTimerDuration Argument type.
type GetRemainingSleepTimerDurationArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetRemainingSleepTimerDuration Response type.
type GetRemainingSleepTimerDurationResponse struct {
	RemainingSleepTimerDuration string `xml:"RemainingSleepTimerDuration"`
	CurrentSleepTimerGeneration uint32 `xml:"CurrentSleepTimerGeneration"`
}

// GetRemainingSleepTimerDuration calls the GetRemainingSleepTimerDuration action on the service.
func (s *Service) GetRemainingSleepTimerDuration(args *GetRemainingSleepTimerDurationArgs) (*GetRemainingSleepTimerDurationResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRemainingSleepTimerDuration",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRemainingSleepTimerDuration: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRemainingSleepTimerDuration == nil {
		return nil, errors.New("unexpected response from service calling GetRemainingSleepTimerDuration()")
	}

	return r.Body.GetRemainingSleepTimerDuration, nil
}

// RunAlarm Argument type.
type RunAlarmArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	InstanceID         uint32 `xml:"InstanceID"`
	AlarmID            uint32 `xml:"AlarmID"`
	LoggedStartTime    string `xml:"LoggedStartTime"`
	Duration           string `xml:"Duration"`
	ProgramURI         string `xml:"ProgramURI"`
	ProgramMetaData    string `xml:"ProgramMetaData"`
	PlayMode           string `xml:"PlayMode"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
}

// RunAlarm Response type.
type RunAlarmResponse struct {
}

// RunAlarm calls the RunAlarm action on the service.
func (s *Service) RunAlarm(args *RunAlarmArgs) (*RunAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RunAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RunAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RunAlarm == nil {
		return nil, errors.New("unexpected response from service calling RunAlarm()")
	}

	return r.Body.RunAlarm, nil
}

// StartAutoplay Argument type.
type StartAutoplayArgs struct {
	Xmlns              string `xml:"xmlns:u,attr"`
	InstanceID         uint32 `xml:"InstanceID"`
	ProgramURI         string `xml:"ProgramURI"`
	ProgramMetaData    string `xml:"ProgramMetaData"`
	Volume             uint16 `xml:"Volume"`
	IncludeLinkedZones bool   `xml:"IncludeLinkedZones"`
	ResetVolumeAfter   bool   `xml:"ResetVolumeAfter"`
}

// StartAutoplay Response type.
type StartAutoplayResponse struct {
}

// StartAutoplay calls the StartAutoplay action on the service.
func (s *Service) StartAutoplay(args *StartAutoplayArgs) (*StartAutoplayResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("StartAutoplay",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{StartAutoplay: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.StartAutoplay == nil {
		return nil, errors.New("unexpected response from service calling StartAutoplay()")
	}

	return r.Body.StartAutoplay, nil
}

// GetRunningAlarmProperties Argument type.
type GetRunningAlarmPropertiesArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetRunningAlarmProperties Response type.
type GetRunningAlarmPropertiesResponse struct {
	AlarmID         uint32 `xml:"AlarmID"`
	GroupID         string `xml:"GroupID"`
	LoggedStartTime string `xml:"LoggedStartTime"`
}

// GetRunningAlarmProperties calls the GetRunningAlarmProperties action on the service.
func (s *Service) GetRunningAlarmProperties(args *GetRunningAlarmPropertiesArgs) (*GetRunningAlarmPropertiesResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRunningAlarmProperties",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRunningAlarmProperties: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRunningAlarmProperties == nil {
		return nil, errors.New("unexpected response from service calling GetRunningAlarmProperties()")
	}

	return r.Body.GetRunningAlarmProperties, nil
}

// SnoozeAlarm Argument type.
type SnoozeAlarmArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Duration   string `xml:"Duration"`
}

// SnoozeAlarm Response type.
type SnoozeAlarmResponse struct {
}

// SnoozeAlarm calls the SnoozeAlarm action on the service.
func (s *Service) SnoozeAlarm(args *SnoozeAlarmArgs) (*SnoozeAlarmResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SnoozeAlarm",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SnoozeAlarm: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SnoozeAlarm == nil {
		return nil, errors.New("unexpected response from service calling SnoozeAlarm()")
	}

	return r.Body.SnoozeAlarm, nil
}

// EndDirectControlSession Argument type.
type EndDirectControlSessionArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// EndDirectControlSession Response type.
type EndDirectControlSessionResponse struct {
}

// EndDirectControlSession calls the EndDirectControlSession action on the service.
func (s *Service) EndDirectControlSession(args *EndDirectControlSessionArgs) (*EndDirectControlSessionResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("EndDirectControlSession",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{EndDirectControlSession: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.EndDirectControlSession == nil {
		return nil, errors.New("unexpected response from service calling EndDirectControlSession()")
	}

	return r.Body.EndDirectControlSession, nil
}

// UpnpEvent represents a UPnP event notification.
type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}

// Property represents a single property in a UPnP event notification.
type Property struct {
	XMLName    xml.Name    `xml:"property"`
	LastChange *LastChange `xml:"LastChange"`
}

// ParseEvent parses a UPnP event notification and updates the service's state variables accordingly.
// It returns a slice of updated state variable values.
func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}

	if err := xml.Unmarshal(body, &evt); err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.LastChange != nil:
			zp.LastChange = prop.LastChange
			events = append(events, *prop.LastChange)
		}
	}
	return events
}
