// Code generated by makeservice based on the provided SCDP XML. DO NOT EDIT.

// Package renderingcontrol is a generated RenderingControl package.
package renderingcontrol

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:RenderingControl:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

// State Variables
type LastChange string

// Service represents RenderingControl service.
type Service struct {
	controlEndpoint *url.URL
	eventEndpoint   *url.URL
	LastChange      *LastChange
	location        *url.URL
	client          *http.Client
}

// NewService creates a new instance of the RenderingControl service.
// You must provide at least a location URL and an HTTP client using the options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaRenderer/RenderingControl/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaRenderer/RenderingControl/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

// ControlEndpoint returns the control endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

// EventEndpoint returns the event endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

// Location returns the base URL of the device hosting the service.
func (s *Service) Location() *url.URL {
	return s.location
}

// Client returns the HTTP client used to communicate with the service.
func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                  xml.Name                      `xml:"s:Body"`
	GetMute                  *GetMuteArgs                  `xml:"u:GetMute,omitempty"`
	SetMute                  *SetMuteArgs                  `xml:"u:SetMute,omitempty"`
	ResetBasicEQ             *ResetBasicEQArgs             `xml:"u:ResetBasicEQ,omitempty"`
	ResetExtEQ               *ResetExtEQArgs               `xml:"u:ResetExtEQ,omitempty"`
	GetVolume                *GetVolumeArgs                `xml:"u:GetVolume,omitempty"`
	SetVolume                *SetVolumeArgs                `xml:"u:SetVolume,omitempty"`
	SetRelativeVolume        *SetRelativeVolumeArgs        `xml:"u:SetRelativeVolume,omitempty"`
	GetVolumeDB              *GetVolumeDBArgs              `xml:"u:GetVolumeDB,omitempty"`
	SetVolumeDB              *SetVolumeDBArgs              `xml:"u:SetVolumeDB,omitempty"`
	GetVolumeDBRange         *GetVolumeDBRangeArgs         `xml:"u:GetVolumeDBRange,omitempty"`
	GetBass                  *GetBassArgs                  `xml:"u:GetBass,omitempty"`
	SetBass                  *SetBassArgs                  `xml:"u:SetBass,omitempty"`
	GetTreble                *GetTrebleArgs                `xml:"u:GetTreble,omitempty"`
	SetTreble                *SetTrebleArgs                `xml:"u:SetTreble,omitempty"`
	GetEQ                    *GetEQArgs                    `xml:"u:GetEQ,omitempty"`
	SetEQ                    *SetEQArgs                    `xml:"u:SetEQ,omitempty"`
	GetLoudness              *GetLoudnessArgs              `xml:"u:GetLoudness,omitempty"`
	SetLoudness              *SetLoudnessArgs              `xml:"u:SetLoudness,omitempty"`
	GetSupportsOutputFixed   *GetSupportsOutputFixedArgs   `xml:"u:GetSupportsOutputFixed,omitempty"`
	GetOutputFixed           *GetOutputFixedArgs           `xml:"u:GetOutputFixed,omitempty"`
	SetOutputFixed           *SetOutputFixedArgs           `xml:"u:SetOutputFixed,omitempty"`
	GetHeadphoneConnected    *GetHeadphoneConnectedArgs    `xml:"u:GetHeadphoneConnected,omitempty"`
	RampToVolume             *RampToVolumeArgs             `xml:"u:RampToVolume,omitempty"`
	RestoreVolumePriorToRamp *RestoreVolumePriorToRampArgs `xml:"u:RestoreVolumePriorToRamp,omitempty"`
	SetChannelMap            *SetChannelMapArgs            `xml:"u:SetChannelMap,omitempty"`
	GetRoomCalibrationStatus *GetRoomCalibrationStatusArgs `xml:"u:GetRoomCalibrationStatus,omitempty"`
	SetRoomCalibrationStatus *SetRoomCalibrationStatusArgs `xml:"u:SetRoomCalibrationStatus,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                  xml.Name                          `xml:"Body"`
	GetMute                  *GetMuteResponse                  `xml:"GetMuteResponse,omitempty"`
	SetMute                  *SetMuteResponse                  `xml:"SetMuteResponse,omitempty"`
	ResetBasicEQ             *ResetBasicEQResponse             `xml:"ResetBasicEQResponse,omitempty"`
	ResetExtEQ               *ResetExtEQResponse               `xml:"ResetExtEQResponse,omitempty"`
	GetVolume                *GetVolumeResponse                `xml:"GetVolumeResponse,omitempty"`
	SetVolume                *SetVolumeResponse                `xml:"SetVolumeResponse,omitempty"`
	SetRelativeVolume        *SetRelativeVolumeResponse        `xml:"SetRelativeVolumeResponse,omitempty"`
	GetVolumeDB              *GetVolumeDBResponse              `xml:"GetVolumeDBResponse,omitempty"`
	SetVolumeDB              *SetVolumeDBResponse              `xml:"SetVolumeDBResponse,omitempty"`
	GetVolumeDBRange         *GetVolumeDBRangeResponse         `xml:"GetVolumeDBRangeResponse,omitempty"`
	GetBass                  *GetBassResponse                  `xml:"GetBassResponse,omitempty"`
	SetBass                  *SetBassResponse                  `xml:"SetBassResponse,omitempty"`
	GetTreble                *GetTrebleResponse                `xml:"GetTrebleResponse,omitempty"`
	SetTreble                *SetTrebleResponse                `xml:"SetTrebleResponse,omitempty"`
	GetEQ                    *GetEQResponse                    `xml:"GetEQResponse,omitempty"`
	SetEQ                    *SetEQResponse                    `xml:"SetEQResponse,omitempty"`
	GetLoudness              *GetLoudnessResponse              `xml:"GetLoudnessResponse,omitempty"`
	SetLoudness              *SetLoudnessResponse              `xml:"SetLoudnessResponse,omitempty"`
	GetSupportsOutputFixed   *GetSupportsOutputFixedResponse   `xml:"GetSupportsOutputFixedResponse,omitempty"`
	GetOutputFixed           *GetOutputFixedResponse           `xml:"GetOutputFixedResponse,omitempty"`
	SetOutputFixed           *SetOutputFixedResponse           `xml:"SetOutputFixedResponse,omitempty"`
	GetHeadphoneConnected    *GetHeadphoneConnectedResponse    `xml:"GetHeadphoneConnectedResponse,omitempty"`
	RampToVolume             *RampToVolumeResponse             `xml:"RampToVolumeResponse,omitempty"`
	RestoreVolumePriorToRamp *RestoreVolumePriorToRampResponse `xml:"RestoreVolumePriorToRampResponse,omitempty"`
	SetChannelMap            *SetChannelMapResponse            `xml:"SetChannelMapResponse,omitempty"`
	GetRoomCalibrationStatus *GetRoomCalibrationStatusResponse `xml:"GetRoomCalibrationStatusResponse,omitempty"`
	SetRoomCalibrationStatus *SetRoomCalibrationStatusResponse `xml:"SetRoomCalibrationStatusResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

// GetMute Argument type.
type GetMuteArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// GetMute Response type.
type GetMuteResponse struct {
	CurrentMute bool `xml:"CurrentMute"`
}

// GetMute calls the GetMute action on the service.
func (s *Service) GetMute(args *GetMuteArgs) (*GetMuteResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetMute",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetMute: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetMute == nil {
		return nil, errors.New("unexpected response from service calling GetMute()")
	}

	return r.Body.GetMute, nil
}

// SetMute Argument type.
type SetMuteArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	InstanceID  uint32 `xml:"InstanceID"`
	Channel     string `xml:"Channel"`
	DesiredMute bool   `xml:"DesiredMute"`
}

// SetMute Response type.
type SetMuteResponse struct {
}

// SetMute calls the SetMute action on the service.
func (s *Service) SetMute(args *SetMuteArgs) (*SetMuteResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetMute",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetMute: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetMute == nil {
		return nil, errors.New("unexpected response from service calling SetMute()")
	}

	return r.Body.SetMute, nil
}

// ResetBasicEQ Argument type.
type ResetBasicEQArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// ResetBasicEQ Response type.
type ResetBasicEQResponse struct {
	Bass        int16  `xml:"Bass"`
	Treble      int16  `xml:"Treble"`
	Loudness    bool   `xml:"Loudness"`
	LeftVolume  uint16 `xml:"LeftVolume"`
	RightVolume uint16 `xml:"RightVolume"`
}

// ResetBasicEQ calls the ResetBasicEQ action on the service.
func (s *Service) ResetBasicEQ(args *ResetBasicEQArgs) (*ResetBasicEQResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ResetBasicEQ",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ResetBasicEQ: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ResetBasicEQ == nil {
		return nil, errors.New("unexpected response from service calling ResetBasicEQ()")
	}

	return r.Body.ResetBasicEQ, nil
}

// ResetExtEQ Argument type.
type ResetExtEQArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	EQType     string `xml:"EQType"`
}

// ResetExtEQ Response type.
type ResetExtEQResponse struct {
}

// ResetExtEQ calls the ResetExtEQ action on the service.
func (s *Service) ResetExtEQ(args *ResetExtEQArgs) (*ResetExtEQResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("ResetExtEQ",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{ResetExtEQ: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.ResetExtEQ == nil {
		return nil, errors.New("unexpected response from service calling ResetExtEQ()")
	}

	return r.Body.ResetExtEQ, nil
}

// GetVolume Argument type.
type GetVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// GetVolume Response type.
type GetVolumeResponse struct {
	CurrentVolume uint16 `xml:"CurrentVolume"`
}

// GetVolume calls the GetVolume action on the service.
func (s *Service) GetVolume(args *GetVolumeArgs) (*GetVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetVolume == nil {
		return nil, errors.New("unexpected response from service calling GetVolume()")
	}

	return r.Body.GetVolume, nil
}

// SetVolume Argument type.
type SetVolumeArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	Channel       string `xml:"Channel"`
	DesiredVolume uint16 `xml:"DesiredVolume"`
}

// SetVolume Response type.
type SetVolumeResponse struct {
}

// SetVolume calls the SetVolume action on the service.
func (s *Service) SetVolume(args *SetVolumeArgs) (*SetVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetVolume == nil {
		return nil, errors.New("unexpected response from service calling SetVolume()")
	}

	return r.Body.SetVolume, nil
}

// SetRelativeVolume Argument type.
type SetRelativeVolumeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
	Adjustment int32  `xml:"Adjustment"`
}

// SetRelativeVolume Response type.
type SetRelativeVolumeResponse struct {
	NewVolume uint16 `xml:"NewVolume"`
}

// SetRelativeVolume calls the SetRelativeVolume action on the service.
func (s *Service) SetRelativeVolume(args *SetRelativeVolumeArgs) (*SetRelativeVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetRelativeVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetRelativeVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetRelativeVolume == nil {
		return nil, errors.New("unexpected response from service calling SetRelativeVolume()")
	}

	return r.Body.SetRelativeVolume, nil
}

// GetVolumeDB Argument type.
type GetVolumeDBArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// GetVolumeDB Response type.
type GetVolumeDBResponse struct {
	CurrentVolume int16 `xml:"CurrentVolume"`
}

// GetVolumeDB calls the GetVolumeDB action on the service.
func (s *Service) GetVolumeDB(args *GetVolumeDBArgs) (*GetVolumeDBResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetVolumeDB",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetVolumeDB: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetVolumeDB == nil {
		return nil, errors.New("unexpected response from service calling GetVolumeDB()")
	}

	return r.Body.GetVolumeDB, nil
}

// SetVolumeDB Argument type.
type SetVolumeDBArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	Channel       string `xml:"Channel"`
	DesiredVolume int16  `xml:"DesiredVolume"`
}

// SetVolumeDB Response type.
type SetVolumeDBResponse struct {
}

// SetVolumeDB calls the SetVolumeDB action on the service.
func (s *Service) SetVolumeDB(args *SetVolumeDBArgs) (*SetVolumeDBResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetVolumeDB",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetVolumeDB: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetVolumeDB == nil {
		return nil, errors.New("unexpected response from service calling SetVolumeDB()")
	}

	return r.Body.SetVolumeDB, nil
}

// GetVolumeDBRange Argument type.
type GetVolumeDBRangeArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// GetVolumeDBRange Response type.
type GetVolumeDBRangeResponse struct {
	MinValue int16 `xml:"MinValue"`
	MaxValue int16 `xml:"MaxValue"`
}

// GetVolumeDBRange calls the GetVolumeDBRange action on the service.
func (s *Service) GetVolumeDBRange(args *GetVolumeDBRangeArgs) (*GetVolumeDBRangeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetVolumeDBRange",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetVolumeDBRange: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetVolumeDBRange == nil {
		return nil, errors.New("unexpected response from service calling GetVolumeDBRange()")
	}

	return r.Body.GetVolumeDBRange, nil
}

// GetBass Argument type.
type GetBassArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetBass Response type.
type GetBassResponse struct {
	CurrentBass int16 `xml:"CurrentBass"`
}

// GetBass calls the GetBass action on the service.
func (s *Service) GetBass(args *GetBassArgs) (*GetBassResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetBass",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetBass: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetBass == nil {
		return nil, errors.New("unexpected response from service calling GetBass()")
	}

	return r.Body.GetBass, nil
}

// SetBass Argument type.
type SetBassArgs struct {
	Xmlns       string `xml:"xmlns:u,attr"`
	InstanceID  uint32 `xml:"InstanceID"`
	DesiredBass int16  `xml:"DesiredBass"`
}

// SetBass Response type.
type SetBassResponse struct {
}

// SetBass calls the SetBass action on the service.
func (s *Service) SetBass(args *SetBassArgs) (*SetBassResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetBass",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetBass: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetBass == nil {
		return nil, errors.New("unexpected response from service calling SetBass()")
	}

	return r.Body.SetBass, nil
}

// GetTreble Argument type.
type GetTrebleArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetTreble Response type.
type GetTrebleResponse struct {
	CurrentTreble int16 `xml:"CurrentTreble"`
}

// GetTreble calls the GetTreble action on the service.
func (s *Service) GetTreble(args *GetTrebleArgs) (*GetTrebleResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetTreble",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetTreble: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetTreble == nil {
		return nil, errors.New("unexpected response from service calling GetTreble()")
	}

	return r.Body.GetTreble, nil
}

// SetTreble Argument type.
type SetTrebleArgs struct {
	Xmlns         string `xml:"xmlns:u,attr"`
	InstanceID    uint32 `xml:"InstanceID"`
	DesiredTreble int16  `xml:"DesiredTreble"`
}

// SetTreble Response type.
type SetTrebleResponse struct {
}

// SetTreble calls the SetTreble action on the service.
func (s *Service) SetTreble(args *SetTrebleArgs) (*SetTrebleResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetTreble",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetTreble: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetTreble == nil {
		return nil, errors.New("unexpected response from service calling SetTreble()")
	}

	return r.Body.SetTreble, nil
}

// GetEQ Argument type.
type GetEQArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	EQType     string `xml:"EQType"`
}

// GetEQ Response type.
type GetEQResponse struct {
	CurrentValue int16 `xml:"CurrentValue"`
}

// GetEQ calls the GetEQ action on the service.
func (s *Service) GetEQ(args *GetEQArgs) (*GetEQResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetEQ",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetEQ: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetEQ == nil {
		return nil, errors.New("unexpected response from service calling GetEQ()")
	}

	return r.Body.GetEQ, nil
}

// SetEQ Argument type.
type SetEQArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	InstanceID   uint32 `xml:"InstanceID"`
	EQType       string `xml:"EQType"`
	DesiredValue int16  `xml:"DesiredValue"`
}

// SetEQ Response type.
type SetEQResponse struct {
}

// SetEQ calls the SetEQ action on the service.
func (s *Service) SetEQ(args *SetEQArgs) (*SetEQResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetEQ",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetEQ: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetEQ == nil {
		return nil, errors.New("unexpected response from service calling SetEQ()")
	}

	return r.Body.SetEQ, nil
}

// GetLoudness Argument type.
type GetLoudnessArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// GetLoudness Response type.
type GetLoudnessResponse struct {
	CurrentLoudness bool `xml:"CurrentLoudness"`
}

// GetLoudness calls the GetLoudness action on the service.
func (s *Service) GetLoudness(args *GetLoudnessArgs) (*GetLoudnessResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetLoudness",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetLoudness: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetLoudness == nil {
		return nil, errors.New("unexpected response from service calling GetLoudness()")
	}

	return r.Body.GetLoudness, nil
}

// SetLoudness Argument type.
type SetLoudnessArgs struct {
	Xmlns           string `xml:"xmlns:u,attr"`
	InstanceID      uint32 `xml:"InstanceID"`
	Channel         string `xml:"Channel"`
	DesiredLoudness bool   `xml:"DesiredLoudness"`
}

// SetLoudness Response type.
type SetLoudnessResponse struct {
}

// SetLoudness calls the SetLoudness action on the service.
func (s *Service) SetLoudness(args *SetLoudnessArgs) (*SetLoudnessResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetLoudness",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetLoudness: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetLoudness == nil {
		return nil, errors.New("unexpected response from service calling SetLoudness()")
	}

	return r.Body.SetLoudness, nil
}

// GetSupportsOutputFixed Argument type.
type GetSupportsOutputFixedArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetSupportsOutputFixed Response type.
type GetSupportsOutputFixedResponse struct {
	CurrentSupportsFixed bool `xml:"CurrentSupportsFixed"`
}

// GetSupportsOutputFixed calls the GetSupportsOutputFixed action on the service.
func (s *Service) GetSupportsOutputFixed(args *GetSupportsOutputFixedArgs) (*GetSupportsOutputFixedResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetSupportsOutputFixed",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetSupportsOutputFixed: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetSupportsOutputFixed == nil {
		return nil, errors.New("unexpected response from service calling GetSupportsOutputFixed()")
	}

	return r.Body.GetSupportsOutputFixed, nil
}

// GetOutputFixed Argument type.
type GetOutputFixedArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetOutputFixed Response type.
type GetOutputFixedResponse struct {
	CurrentFixed bool `xml:"CurrentFixed"`
}

// GetOutputFixed calls the GetOutputFixed action on the service.
func (s *Service) GetOutputFixed(args *GetOutputFixedArgs) (*GetOutputFixedResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetOutputFixed",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetOutputFixed: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetOutputFixed == nil {
		return nil, errors.New("unexpected response from service calling GetOutputFixed()")
	}

	return r.Body.GetOutputFixed, nil
}

// SetOutputFixed Argument type.
type SetOutputFixedArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	InstanceID   uint32 `xml:"InstanceID"`
	DesiredFixed bool   `xml:"DesiredFixed"`
}

// SetOutputFixed Response type.
type SetOutputFixedResponse struct {
}

// SetOutputFixed calls the SetOutputFixed action on the service.
func (s *Service) SetOutputFixed(args *SetOutputFixedArgs) (*SetOutputFixedResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetOutputFixed",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetOutputFixed: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetOutputFixed == nil {
		return nil, errors.New("unexpected response from service calling SetOutputFixed()")
	}

	return r.Body.SetOutputFixed, nil
}

// GetHeadphoneConnected Argument type.
type GetHeadphoneConnectedArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetHeadphoneConnected Response type.
type GetHeadphoneConnectedResponse struct {
	CurrentHeadphoneConnected bool `xml:"CurrentHeadphoneConnected"`
}

// GetHeadphoneConnected calls the GetHeadphoneConnected action on the service.
func (s *Service) GetHeadphoneConnected(args *GetHeadphoneConnectedArgs) (*GetHeadphoneConnectedResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetHeadphoneConnected",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetHeadphoneConnected: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetHeadphoneConnected == nil {
		return nil, errors.New("unexpected response from service calling GetHeadphoneConnected()")
	}

	return r.Body.GetHeadphoneConnected, nil
}

// RampToVolume Argument type.
type RampToVolumeArgs struct {
	Xmlns            string `xml:"xmlns:u,attr"`
	InstanceID       uint32 `xml:"InstanceID"`
	Channel          string `xml:"Channel"`
	RampType         string `xml:"RampType"`
	DesiredVolume    uint16 `xml:"DesiredVolume"`
	ResetVolumeAfter bool   `xml:"ResetVolumeAfter"`
	ProgramURI       string `xml:"ProgramURI"`
}

// RampToVolume Response type.
type RampToVolumeResponse struct {
	RampTime uint32 `xml:"RampTime"`
}

// RampToVolume calls the RampToVolume action on the service.
func (s *Service) RampToVolume(args *RampToVolumeArgs) (*RampToVolumeResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RampToVolume",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RampToVolume: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RampToVolume == nil {
		return nil, errors.New("unexpected response from service calling RampToVolume()")
	}

	return r.Body.RampToVolume, nil
}

// RestoreVolumePriorToRamp Argument type.
type RestoreVolumePriorToRampArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	Channel    string `xml:"Channel"`
}

// RestoreVolumePriorToRamp Response type.
type RestoreVolumePriorToRampResponse struct {
}

// RestoreVolumePriorToRamp calls the RestoreVolumePriorToRamp action on the service.
func (s *Service) RestoreVolumePriorToRamp(args *RestoreVolumePriorToRampArgs) (*RestoreVolumePriorToRampResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("RestoreVolumePriorToRamp",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{RestoreVolumePriorToRamp: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.RestoreVolumePriorToRamp == nil {
		return nil, errors.New("unexpected response from service calling RestoreVolumePriorToRamp()")
	}

	return r.Body.RestoreVolumePriorToRamp, nil
}

// SetChannelMap Argument type.
type SetChannelMapArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
	ChannelMap string `xml:"ChannelMap"`
}

// SetChannelMap Response type.
type SetChannelMapResponse struct {
}

// SetChannelMap calls the SetChannelMap action on the service.
func (s *Service) SetChannelMap(args *SetChannelMapArgs) (*SetChannelMapResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetChannelMap",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetChannelMap: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetChannelMap == nil {
		return nil, errors.New("unexpected response from service calling SetChannelMap()")
	}

	return r.Body.SetChannelMap, nil
}

// GetRoomCalibrationStatus Argument type.
type GetRoomCalibrationStatusArgs struct {
	Xmlns      string `xml:"xmlns:u,attr"`
	InstanceID uint32 `xml:"InstanceID"`
}

// GetRoomCalibrationStatus Response type.
type GetRoomCalibrationStatusResponse struct {
	RoomCalibrationEnabled   bool `xml:"RoomCalibrationEnabled"`
	RoomCalibrationAvailable bool `xml:"RoomCalibrationAvailable"`
}

// GetRoomCalibrationStatus calls the GetRoomCalibrationStatus action on the service.
func (s *Service) GetRoomCalibrationStatus(args *GetRoomCalibrationStatusArgs) (*GetRoomCalibrationStatusResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetRoomCalibrationStatus",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetRoomCalibrationStatus: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetRoomCalibrationStatus == nil {
		return nil, errors.New("unexpected response from service calling GetRoomCalibrationStatus()")
	}

	return r.Body.GetRoomCalibrationStatus, nil
}

// SetRoomCalibrationStatus Argument type.
type SetRoomCalibrationStatusArgs struct {
	Xmlns                  string `xml:"xmlns:u,attr"`
	InstanceID             uint32 `xml:"InstanceID"`
	RoomCalibrationEnabled bool   `xml:"RoomCalibrationEnabled"`
}

// SetRoomCalibrationStatus Response type.
type SetRoomCalibrationStatusResponse struct {
}

// SetRoomCalibrationStatus calls the SetRoomCalibrationStatus action on the service.
func (s *Service) SetRoomCalibrationStatus(args *SetRoomCalibrationStatusArgs) (*SetRoomCalibrationStatusResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("SetRoomCalibrationStatus",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{SetRoomCalibrationStatus: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.SetRoomCalibrationStatus == nil {
		return nil, errors.New("unexpected response from service calling SetRoomCalibrationStatus()")
	}

	return r.Body.SetRoomCalibrationStatus, nil
}

// UpnpEvent represents a UPnP event notification.
type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}

// Property represents a single property in a UPnP event notification.
type Property struct {
	XMLName    xml.Name    `xml:"property"`
	LastChange *LastChange `xml:"LastChange"`
}

// ParseEvent parses a UPnP event notification and updates the service's state variables accordingly.
// It returns a slice of updated state variable values.
func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}

	if err := xml.Unmarshal(body, &evt); err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.LastChange != nil:
			zp.LastChange = prop.LastChange
			events = append(events, *prop.LastChange)
		}
	}
	return events
}
