// Code generated by makeservice based on the provided SCDP XML. DO NOT EDIT.

// Package connectionmanager is a generated ConnectionManager package.
package connectionmanager

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"net/http"
	"net/url"
)

const (
	ServiceURN     = "urn:schemas-upnp-org:service:ConnectionManager:1"
	EncodingSchema = "http://schemas.xmlsoap.org/soap/encoding/"
	EnvelopeSchema = "http://schemas.xmlsoap.org/soap/envelope/"
)

type ServiceOption func(*Service)

func WithClient(c *http.Client) ServiceOption {
	return func(s *Service) {
		s.client = c
	}
}

func WithLocation(u *url.URL) ServiceOption {
	return func(s *Service) {
		s.location = u
	}
}

// Enumerations
type ConnectionStatusEnum string

const (
	ConnectionStatus_OK                    ConnectionStatusEnum = "OK"
	ConnectionStatus_ContentFormatMismatch ConnectionStatusEnum = "ContentFormatMismatch"
	ConnectionStatus_InsufficientBandwidth ConnectionStatusEnum = "InsufficientBandwidth"
	ConnectionStatus_UnreliableChannel     ConnectionStatusEnum = "UnreliableChannel"
	ConnectionStatus_Unknown               ConnectionStatusEnum = "Unknown"
)

type DirectionEnum string

const (
	Direction_Input  DirectionEnum = "Input"
	Direction_Output DirectionEnum = "Output"
)

// State Variables
type SourceProtocolInfo string
type SinkProtocolInfo string
type CurrentConnectionIDs string

// Service represents ConnectionManager service.
type Service struct {
	controlEndpoint      *url.URL
	eventEndpoint        *url.URL
	SourceProtocolInfo   *SourceProtocolInfo
	SinkProtocolInfo     *SinkProtocolInfo
	CurrentConnectionIDs *CurrentConnectionIDs
	location             *url.URL
	client               *http.Client
}

// NewService creates a new instance of the ConnectionManager service.
// You must provide at least a location URL and an HTTP client using the options.
func NewService(opts ...ServiceOption) *Service {
	s := &Service{}

	c, err := url.Parse("/MediaServer/ConnectionManager/Control")
	if nil != err {
		panic(err)
	}
	e, err := url.Parse("/MediaServer/ConnectionManager/Event")
	if nil != err {
		panic(err)
	}

	for _, opt := range opts {
		opt(s)
	}

	if s.client == nil {
		panic("no client location")
	}
	if s.location == nil {
		panic("empty location")
	}

	s.controlEndpoint = s.location.ResolveReference(c)
	s.eventEndpoint = s.location.ResolveReference(e)

	return s
}

// ControlEndpoint returns the control endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) ControlEndpoint() *url.URL {
	return s.controlEndpoint
}

// EventEndpoint returns the event endpoint URL of the service.
// This is usually a URL relative to the device's base URL.
func (s *Service) EventEndpoint() *url.URL {
	return s.eventEndpoint
}

// Location returns the base URL of the device hosting the service.
func (s *Service) Location() *url.URL {
	return s.location
}

// Client returns the HTTP client used to communicate with the service.
func (s *Service) Client() *http.Client {
	return s.client
}

// internal use only
type envelope struct {
	XMLName       xml.Name `xml:"s:Envelope"`
	Xmlns         string   `xml:"xmlns:s,attr"`
	EncodingStyle string   `xml:"s:encodingStyle,attr"`
	Body          body     `xml:"s:Body"`
}

// internal use only
type body struct {
	XMLName                  xml.Name                      `xml:"s:Body"`
	GetProtocolInfo          *GetProtocolInfoArgs          `xml:"u:GetProtocolInfo,omitempty"`
	GetCurrentConnectionIDs  *GetCurrentConnectionIDsArgs  `xml:"u:GetCurrentConnectionIDs,omitempty"`
	GetCurrentConnectionInfo *GetCurrentConnectionInfoArgs `xml:"u:GetCurrentConnectionInfo,omitempty"`
}

// internal use only
type envelopeResponse struct {
	XMLName       xml.Name     `xml:"Envelope"`
	Xmlns         string       `xml:"xmlns:s,attr"`
	EncodingStyle string       `xml:"encodingStyle,attr"`
	Body          bodyResponse `xml:"Body"`
}

// internal use only
type bodyResponse struct {
	XMLName                  xml.Name                          `xml:"Body"`
	GetProtocolInfo          *GetProtocolInfoResponse          `xml:"GetProtocolInfoResponse,omitempty"`
	GetCurrentConnectionIDs  *GetCurrentConnectionIDsResponse  `xml:"GetCurrentConnectionIDsResponse,omitempty"`
	GetCurrentConnectionInfo *GetCurrentConnectionInfoResponse `xml:"GetCurrentConnectionInfoResponse,omitempty"`
}

func (s *Service) exec(actionName string, envelope *envelope) (*envelopeResponse, error) {
	postBody, err := xml.Marshal(envelope)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", s.controlEndpoint.String(), bytes.NewBuffer(postBody))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/xml; charset=\"utf-8\"")
	req.Header.Set("SOAPAction", ServiceURN+"#"+actionName)
	res, err := s.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	responseBody, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	var envelopeResponse envelopeResponse
	err = xml.Unmarshal(responseBody, &envelopeResponse)
	if err != nil {
		return nil, err
	}
	return &envelopeResponse, nil
}

// GetProtocolInfo Argument type.
type GetProtocolInfoArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}

// GetProtocolInfo Response type.
type GetProtocolInfoResponse struct {
	Source string `xml:"Source"`
	Sink   string `xml:"Sink"`
}

// GetProtocolInfo calls the GetProtocolInfo action on the service.
func (s *Service) GetProtocolInfo(args *GetProtocolInfoArgs) (*GetProtocolInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetProtocolInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetProtocolInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetProtocolInfo == nil {
		return nil, errors.New("unexpected response from service calling GetProtocolInfo()")
	}

	return r.Body.GetProtocolInfo, nil
}

// GetCurrentConnectionIDs Argument type.
type GetCurrentConnectionIDsArgs struct {
	Xmlns string `xml:"xmlns:u,attr"`
}

// GetCurrentConnectionIDs Response type.
type GetCurrentConnectionIDsResponse struct {
	ConnectionIDs string `xml:"ConnectionIDs"`
}

// GetCurrentConnectionIDs calls the GetCurrentConnectionIDs action on the service.
func (s *Service) GetCurrentConnectionIDs(args *GetCurrentConnectionIDsArgs) (*GetCurrentConnectionIDsResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCurrentConnectionIDs",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCurrentConnectionIDs: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCurrentConnectionIDs == nil {
		return nil, errors.New("unexpected response from service calling GetCurrentConnectionIDs()")
	}

	return r.Body.GetCurrentConnectionIDs, nil
}

// GetCurrentConnectionInfo Argument type.
type GetCurrentConnectionInfoArgs struct {
	Xmlns        string `xml:"xmlns:u,attr"`
	ConnectionID int32  `xml:"ConnectionID"`
}

// GetCurrentConnectionInfo Response type.
type GetCurrentConnectionInfoResponse struct {
	RcsID                 int32                `xml:"RcsID"`
	AVTransportID         int32                `xml:"AVTransportID"`
	ProtocolInfo          string               `xml:"ProtocolInfo"`
	PeerConnectionManager string               `xml:"PeerConnectionManager"`
	PeerConnectionID      int32                `xml:"PeerConnectionID"`
	Direction             DirectionEnum        `xml:"Direction"`
	Status                ConnectionStatusEnum `xml:"Status"`
}

// GetCurrentConnectionInfo calls the GetCurrentConnectionInfo action on the service.
func (s *Service) GetCurrentConnectionInfo(args *GetCurrentConnectionInfoArgs) (*GetCurrentConnectionInfoResponse, error) {
	args.Xmlns = ServiceURN
	r, err := s.exec("GetCurrentConnectionInfo",
		&envelope{
			EncodingStyle: EncodingSchema,
			Xmlns:         EnvelopeSchema,
			Body:          body{GetCurrentConnectionInfo: args},
		})
	if err != nil {
		return nil, err
	}
	if r.Body.GetCurrentConnectionInfo == nil {
		return nil, errors.New("unexpected response from service calling GetCurrentConnectionInfo()")
	}

	return r.Body.GetCurrentConnectionInfo, nil
}

// UpnpEvent represents a UPnP event notification.
type UpnpEvent struct {
	XMLName      xml.Name   `xml:"propertyset"`
	XMLNameSpace string     `xml:"xmlns:e,attr"`
	Properties   []Property `xml:"property"`
}

// Property represents a single property in a UPnP event notification.
type Property struct {
	XMLName              xml.Name              `xml:"property"`
	SourceProtocolInfo   *SourceProtocolInfo   `xml:"SourceProtocolInfo"`
	SinkProtocolInfo     *SinkProtocolInfo     `xml:"SinkProtocolInfo"`
	CurrentConnectionIDs *CurrentConnectionIDs `xml:"CurrentConnectionIDs"`
}

// ParseEvent parses a UPnP event notification and updates the service's state variables accordingly.
// It returns a slice of updated state variable values.
func (zp *Service) ParseEvent(body []byte) []interface{} {
	var evt UpnpEvent
	var events []interface{}

	if err := xml.Unmarshal(body, &evt); err != nil {
		return events
	}
	for _, prop := range evt.Properties {
		_ = prop
		switch {
		case prop.SourceProtocolInfo != nil:
			zp.SourceProtocolInfo = prop.SourceProtocolInfo
			events = append(events, *prop.SourceProtocolInfo)
		case prop.SinkProtocolInfo != nil:
			zp.SinkProtocolInfo = prop.SinkProtocolInfo
			events = append(events, *prop.SinkProtocolInfo)
		case prop.CurrentConnectionIDs != nil:
			zp.CurrentConnectionIDs = prop.CurrentConnectionIDs
			events = append(events, *prop.CurrentConnectionIDs)
		}
	}
	return events
}
